---
- include: hostname.yml
  when: webtier_hostname is defined
  tags: [webtier, webtier-hostname]

- include: packages.yml
  tags: [webtier, webtier-packages]

- include: repos.yml
  tags: [webtier, webtier-repos]

- include: seagull.yml
  when: webtier_seagull_deploy
  tags: [webtier, webtier-seagull]

- include: vpn.yml
  when: webtier_vpn_config is defined
  tags: [webtier, webtier-vpn]
