---
- import_tasks: hostname.yml
  when: webtier_hostname is defined
  tags: [webtier, webtier-hostname]

- import_tasks: packages.yml
  tags: [webtier, webtier-packages]

- import_tasks: repos.yml
  tags: [webtier, webtier-repos]

- import_tasks: seagull.yml
  when: not webtier_skip_seagull
  tags: [webtier, webtier-seagull]

- import_tasks: vpn.yml
  when: webtier_vpn_config is defined
  tags: [webtier, webtier-vpn]
